#!/bin/sh

# Perl wants to rewrite these files.
pwd | grep '/tmp/' && chmod  u+w const-*.inc

if [ -f Makefile.PL ]; then
    $PERL Makefile.PL || exit 1
    make || exit 1
#    make test || exit 1
    make install DESTDIR=$DESTDIR || exit 1
#    find $DESTDIR -name perllocal.pod -type f -exec rm {} \;
#    find $DESTDIR -name .packlist -type f -exec rm {} \;
fi

